### ISSUE TITLE
Specify no recombination rate

### ISSUE THREAD

**Issue by lpettrich** [TPPSellinger/eSMC2#1]
Hello there, 

I am working with genomic data of an ancient parthenogenetic nematode species. Therfore, its recombination rate should be close to 0 but we do not know for sure. That is why I was wondering if I can use your tool without specifiying a recombination rate?
If possible, how would I do that? 
I appreciate your help. 

Best,
Laura Pettrich

**Comment by TPPSellinger** [comment]
Hello Laura,  

Can you tell me what you are trying to infer ?  As first analysis I would try to estimate the ratio of recombinaton  over mutation  (rho/theta) and make sure it is very small (in the parameters of eSMC or eSMC2 you can set Boxr=c(3,3) ).  If you are searching for selfing or signature of parthenogenesis it would decrease this value even more. If you don't observe a very small recombination rate, it might suggest that something else is going on.

From my side I never ran eSMC on data with recombination rate equal to 0. I will perform simulations and look at it. I will come back at you in couples of days with the results. In addition, we will soon submit ( ~ 2 weeks) a new paper and I will update the current version of eSMC2. You might want to wait for this new version as it offers new features which could help you with this problem. 

Best,

Thibaut Sellinger

**Comment by lpettrich** [comment]
Hello Thibaut,

Thank you for your quick reply. It is really great to hear that you will update eSMC2 soon, looking forward to this since we think about implementing this tool in upcoming experiments. Right now I intend to test this tool in a small project and look at the data I get from two different species. So right now it is my first look at your tool. 

What info would you need exactly? This nematode species is a really challenging case because it is not only pathenogenetic but it was also in a dormant stage for a very long time. So I intend to look especially at the signature of dormancy but the signature of selfing would also be intersting to infer.  Maybe this species has too complex life traits to infer its history at the moment but nevertheless we wanted to try. 

Thanks a lot for offering to run simulations with the recombination rate equal to 0. In the meantime I will try to implement your suggestions. How would you calculate the ratio using Boxr=c(3,3)?

Best,
Laura Pettrich

**Comment by TPPSellinger** [comment]
Hello ! 

Good News ! I did some simulations and eSMC2 should be able to tell you if recombination rate is null or not (I find a recombination rate of  ~  10^-17, convergence can be quite slow and take some time).  However, the problem is now that SMC methods do not perform good in absence of recombination events (so you can give up on recovering the demographic history if the recombination rate is really small   https://doi.org/10.1111/1755-0998.13416  ). 

If you do not know the recombination rate (and have no idea of it's potential values), I would give up using eSMC2 to search for parthenogenesis or dormancy.  However if you have boundaries on the potential values of the recombination rates, I would uses those two values to run eSMC2 ( and to still estimate rho/theta). If in both cases, the rho/theta you find is smaller than what is expected, it means that a latent mechanism is diminishing rho/theta. It could  either be dormancy, parthenogenesis or both. Disentangling form both effect is the tricky part and cannot really help you. But this could help you to point toward a direction. if you have selfing (or parthenogenesis), i expect that diversity within individual will be less than diversity between individuals (you might want to read more about this). However, dormancy will simply increase diversity will not lead to such effect. 

The best case would be if you had a sister species or population (and can assume they share recombination rate) and knew that the other population does not do dormancy or parthenogenesis. You could then simply infer in both case rho/theta, and impute the difference between the two estimated value to either dormancy and/or parthenogenesis and infer their rates (without requiring to actually know the recombination rate). 

I will try to have the new version of eSMC2 uploaded within two weeks and will also update the tutorial for you so that you can run what I suggested.

I hope this will help you ; best,

Thibaut

PS: to calculate the ratio you can simply do : result = eSMC2(....) ;  rec/mu =  (result$rho/result$mu)
